fprintf('Real number in range (0, 30)        : %d\n', rand()*30)
fprintf('Real number in range (10, 100)         : %d\n', rand()*90+10)
fprintf('Integer inclusive range from 1 to 20   : %d\n', randi([1 20]))
fprintf('Integer inclusive range from 0 to 20   : %d\n', randi([0 20]))
fprintf('Integer inclusive range from 30 to 80  : %d\n', randi([30 80]))